# -*- coding: utf-8 -*-
"""Atividade de robótica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rlyYh5A-Vx5KPdvIK-RLwrsnGXg3q-V
"""

import numpy as np
import math

def SE2_xy(x,y):
  matriz = np.array([[1,0,x],[0,1,y],[0,0,1]])
  return matriz

def SE2_theta(theta):
  matriz = np.array([[math.cos(theta),-math.sin(theta),0],[math.sin(theta),math.cos(theta),0],[0,0,1]])
  return matriz

def transform(xi,theta, p, inv: bool):
    R = SE2_theta(theta)
    T = SE2_xy(xi[0], xi[1]) @ R

    if(inv):
        T = np.linalg.inv(T)

    p_hom = np.array([p[0], p[1], 1.0])
    return T @ p_hom

def tests():
  #test1
  entrada = (1, 0.25)
  theta = 0
  p = (0.5, 0.5)
  result = transform(entrada, theta, p, False)
  print(f"Test Result 1: ({result[0]},{result[1]})")

  #test2
  entrada = (1, 0.25)
  theta = 0
  p = (0.5, 0.5)
  result = transform(entrada, theta, p, True)
  print(f"Test Result 2: ({result[0]},{result[1]})")

  #test3
  entrada = (1, 0.25)
  theta = np.pi/4
  p = (0.5, 0.5)
  result = transform(entrada, theta, p, False)
  print(f"Test Result 3: ({result[0]},{result[1]})")

  #test4
  entrada = (1, 0.25)
  theta = np.pi/4
  p = (0.5, 0.5)
  result = transform(entrada, theta, p, True)
  print(f"Test Result 4: ({result[0]},{result[1]})")

tests()